version: 1.0.{build}
os: Visual Studio 2013

install:
 - git submodule update --init --recursive

build_script:
   - mkdir build
   - cd build
   - cmake .. -DSDL_STATIC=0 -DSDL_SHARED=1 -DBUILD_SHARED_LIBS=0 -DYUME_BUILD_DIRECT3D11=1
